-- Sort-friendly index for the public /words listing query.
--
-- Background. The hot query path generated by PostgREST for
-- `/api/words?freq=必备词` (and the analogous `?semantic=…`) is roughly:
--
--   SELECT id, slug, …, count(*) OVER () AS total
--   FROM words
--   WHERE is_published = true
--     AND is_deleted = false
--     AND metadata @> '{"word_freq":"必备词"}'
--   ORDER BY lemma
--   LIMIT 60 OFFSET 0;
--
-- The GIN index added in 0008_word_filter_facets.sql
-- (idx_words_public_metadata_filter) handles the @> predicate efficiently.
-- But after the GIN scan returns ~1800 candidate rows, the planner still has
-- to:
--   1. sort them by lemma (no index → in-memory quicksort), and
--   2. materialise the full filtered set so `count(*) OVER ()` knows the
--      total — `{ count: 'exact' }` in PostgREST is implemented as a window
--      aggregate, which is forced to read every matching row.
--
-- On Supabase's small free-tier compute the combined GIN-bitmap → sort →
-- window cycle has been observed to exceed the 8s statement_timeout under
-- concurrent load, which is why production was returning
-- `canceling statement due to statement timeout` for `?freq=必备词`.
--
-- Fix. A btree index on (lemma) over the same `is_published AND NOT
-- is_deleted` slice lets the planner fall back to an index scan in lemma
-- order whenever the GIN bitmap-scan path is too narrow to amortise the
-- sort. With both indexes available it can pick whichever it estimates is
-- cheaper for a given filter selectivity.
--
-- Application-side commit dc06515 added a JS-filter fallback so the user
-- never sees `total: 0` even if the query still times out, but that
-- fallback walks the full 5k-row corpus and is strictly slower than the DB
-- path. This index lets the fast path actually be fast.

create index if not exists idx_words_public_lemma_sort
  on public.words (lemma)
  where is_published = true and is_deleted = false;

-- Idempotent re-issue of the metadata GIN index from 0008. Some Supabase
-- replicas in this project's history have been rebuilt or branched off
-- before 0008 ran; `CREATE INDEX IF NOT EXISTS` is a no-op when the
-- partial index already exists, so it's safe to keep both migrations.
create index if not exists idx_words_public_metadata_filter
  on public.words using gin (metadata jsonb_path_ops)
  where is_published = true and is_deleted = false;

-- Document the index pair so future contributors don't drop one without
-- understanding the interaction.
comment on index public.idx_words_public_lemma_sort is
  'Partial btree on lemma for the published/non-deleted slice. Pairs with idx_words_public_metadata_filter (GIN on metadata) to keep the public /words listing under the Supabase statement_timeout when filtered by semantic_field or word_freq with ORDER BY lemma + count: exact.';

comment on index public.idx_words_public_metadata_filter is
  'Partial GIN on metadata jsonb_path_ops for the published/non-deleted slice. Drives @> containment lookups for semantic_field and word_freq filters; pairs with idx_words_public_lemma_sort for the ORDER BY lemma path.';
